### PR TITLE
Created a simple compile time string and fixed a bunch of docs.

### PR DESCRIPTION
**Pull request by Sqeaky**
This is to make good on promises made in the exception stuff, and it was easy.

### CODE REVIEW

**Comment by Sqeaky** [comment]
Hey Jenkins, where is the empscripten build?

**Comment by MakoEnergy** [comment]
A few things regarding documentation, styling, and code.

Documentation:
You added "(or more)" to our fixed size types.  It is my understanding that those types are guaranteed to be exactly those sizes.  The types are optional, but their guarantee isn't.
http://www.cplusplus.com/reference/cstdint/
http://en.cppreference.com/w/cpp/types/integer
operator[] is missing param and return documentation.

Styling:
Class member indentation.  Also you alternate between public and private as you go down the class.  The members should be more cleanly sorted.
If you are trying to maintain maximum compatibility with standard types, then I'm ok with the names "c_str" and "str" for conversion methods.  Otherwise the names should be more clear.

Code:
If it's empty, why bother with staticstring.cpp?
I see you are using a recursive algorithm, is there a chance that really long strings would trip the mechanism for detecting infinite recursion and crash the program?

**Comment by Sqeaky** [comment]
I think there is no chance of this crashing the program, it should be resolved by the compiler and only a constant string should be included. Accidentally using this type with run time types is hard, but if done that could cause neat problems. For reference string concatenation with + generates a linear amount of types and consumes a quadratic amount of time and resources during compile time to produce the static value in the final executable.

I did name str and c_str that way for compatibility purposes. Should I make alias methods? GetString() GetCharString()? I saw no specific use, but thought maybe this could be used in templates or somethign just a little easier.

For the type size, I was concerned about loosening guarantees to provide space for future changes. I will read on type again and see if that is actually required.

I will look into styling, the ordering is not as free as I would like.... templates. You and I still disagree on indentation... I will fix the docs and look into travis and appveyor like you mentioned.

**Comment by MakoEnergy** [comment]
To be more clear about indentation, we don't agree on every matter of indentation, but specifically having access specifiers be on the same indentation as the curly brackets, and the members be one more than that is something we have discussed a few times and I thought we had resolved.

**Comment by Sqeaky** [comment]
Hey Jenkins, where is the empscripten build?

**Comment by Sqeaky** [comment]
Hey Jenkins, can you build again, I want to test the new firewall rules don't reset on reboot again.

**Comment by Sqeaky** [comment]
Hey Jenkins!

**Pull request merged**
